/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BsbSideDrawer {
    'opened': boolean;
    'toggle': () => Promise<void>;
  }
}

declare global {


  interface HTMLBsbSideDrawerElement extends Components.BsbSideDrawer, HTMLStencilElement {}
  var HTMLBsbSideDrawerElement: {
    prototype: HTMLBsbSideDrawerElement;
    new (): HTMLBsbSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'bsb-side-drawer': HTMLBsbSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface BsbSideDrawer extends JSXBase.HTMLAttributes<HTMLBsbSideDrawerElement> {
    'opened'?: boolean;
  }

  interface IntrinsicElements {
    'bsb-side-drawer': BsbSideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


